/*
The Application tab is most useful when you have an page that deals with cookies or local storage. You can go to this tab and see every cookie that a page has. You can see what's in your cache or your session storage if you need to see what's happening with your updates not showing.
Chrome DevTools
Get started with viewing and changing the DOM. ...
View the properties of DOM objects. ...
View and change CSS. ...
Inspect CSS grid. ...
Inspect and Debug CSS Flexbox Layouts. ...
Inspect and debug CSS container queries. ...
CSS features reference. ...
Badges reference.
*/